// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for RotateSecretFunction
 */
export interface RotateSecretFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/rotate-secret.
 */
export class RotateSecretFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: RotateSecretFunctionProps) {
    super(scope, id, {
      description: 'src/rotate-secret.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs16.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../assets/rotate-secret.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}